name: serinus_loxia
description: A Serinus plugin that integrates Loxia, a lightweight Dart ORM for Relational Databases, to provide seamless database interactions within Serinus applications.
version: 1.0.0
repository: https://github.com/avesbox/serinus_loxia
documentation: https://serinus.app
homepage: https://serinus.app
funding:
  - https://github.com/sponsors/francescovallone
topics:
  - serinus
  - loxia
  - orm
  - database
  - backend

environment:
  sdk: '>=3.9.0 <4.0.0'

dependencies:
  path: ^1.9.0
  serinus: ^2.1.0
  loxia: '>=0.0.11 <0.1.0'

dev_dependencies:
  build_runner: ^2.11.1
  lints: ^6.0.0
  test: ^1.25.6
